// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperaturecontrolservice.proto

package com.example.temperaturecontrolservice;

public interface GetTemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperaturecontrolservice.GetTemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperature = 1;</code>
   */
  double getTemperature();
}
