// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperaturecontrolservice.proto

package com.example.temperaturecontrolservice;

public interface GetTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperaturecontrolservice.GetTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area_id = 1;</code>
   */
  java.lang.String getAreaId();
  /**
   * <code>string area_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaIdBytes();
}
