// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperaturecontrolservice.proto

package com.example.temperaturecontrolservice;

public interface SetTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperaturecontrolservice.SetTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area_id = 1;</code>
   */
  java.lang.String getAreaId();
  /**
   * <code>string area_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaIdBytes();

  /**
   * <code>double temperature = 2;</code>
   */
  double getTemperature();
}
