// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperaturecontrolservice.proto

package com.example.temperaturecontrolservice;

public interface SetTemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperaturecontrolservice.SetTemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
