// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temperaturecontrolservice.proto

package com.example.temperaturecontrolservice;

public final class TemperatureControlServiceProto {
  private TemperatureControlServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperaturecontrolservice_SetTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperaturecontrolservice_SetTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperaturecontrolservice_SetTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperaturecontrolservice_SetTemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperaturecontrolservice_GetTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperaturecontrolservice_GetTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temperaturecontrolservice_GetTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_temperaturecontrolservice_GetTemperatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037temperaturecontrolservice.proto\022\031tempe" +
      "raturecontrolservice\"=\n\025SetTemperatureRe" +
      "quest\022\017\n\007area_id\030\001 \001(\t\022\023\n\013temperature\030\002 " +
      "\001(\001\")\n\026SetTemperatureResponse\022\017\n\007message" +
      "\030\001 \001(\t\"(\n\025GetTemperatureRequest\022\017\n\007area_" +
      "id\030\001 \001(\t\"-\n\026GetTemperatureResponse\022\023\n\013te" +
      "mperature\030\001 \001(\0012\211\002\n\031TemperatureControlSe" +
      "rvice\022u\n\016SetTemperature\0220.temperaturecon" +
      "trolservice.SetTemperatureRequest\0321.temp" +
      "eraturecontrolservice.SetTemperatureResp" +
      "onse\022u\n\016GetTemperature\0220.temperaturecont" +
      "rolservice.GetTemperatureRequest\0321.tempe" +
      "raturecontrolservice.GetTemperatureRespo" +
      "nseBI\n%com.example.temperaturecontrolser" +
      "viceB\036TemperatureControlServiceProtoP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_temperaturecontrolservice_SetTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_temperaturecontrolservice_SetTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperaturecontrolservice_SetTemperatureRequest_descriptor,
        new java.lang.String[] { "AreaId", "Temperature", });
    internal_static_temperaturecontrolservice_SetTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_temperaturecontrolservice_SetTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperaturecontrolservice_SetTemperatureResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_temperaturecontrolservice_GetTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_temperaturecontrolservice_GetTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperaturecontrolservice_GetTemperatureRequest_descriptor,
        new java.lang.String[] { "AreaId", });
    internal_static_temperaturecontrolservice_GetTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_temperaturecontrolservice_GetTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_temperaturecontrolservice_GetTemperatureResponse_descriptor,
        new java.lang.String[] { "Temperature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
