// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: securitycameraservice.proto

package com.example.smartsurveillancesecurityservice;

public interface CameraResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:securitycameraservice.CameraResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string camera_id = 1;</code>
   */
  java.lang.String getCameraId();
  /**
   * <code>string camera_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraIdBytes();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
