// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: securitycameraservice.proto

package com.example.smartsurveillancesecurityservice;

public interface CameraRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:securitycameraservice.CameraRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string camera_id = 1;</code>
   */
  java.lang.String getCameraId();
  /**
   * <code>string camera_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraIdBytes();
}
