// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accesscontrolservice.proto

package com.example.accesscontrolservice;

public final class AccessControlServiceProto {
  private AccessControlServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accesscontrolservice_AccessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accesscontrolservice_AccessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accesscontrolservice_AccessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accesscontrolservice_AccessResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accesscontrolservice_RevokeAccessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accesscontrolservice_RevokeAccessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_accesscontrolservice_RevokeAccessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_accesscontrolservice_RevokeAccessResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032accesscontrolservice.proto\022\024accesscont" +
      "rolservice\"J\n\rAccessRequest\022\017\n\007user_id\030\001" +
      " \001(\t\022\017\n\007area_id\030\002 \001(\t\022\027\n\017access_duration" +
      "\030\003 \001(\005\"!\n\016AccessResponse\022\017\n\007message\030\001 \001(" +
      "\t\"7\n\023RevokeAccessRequest\022\017\n\007user_id\030\001 \001(" +
      "\t\022\017\n\007area_id\030\002 \001(\t\"\'\n\024RevokeAccessRespon" +
      "se\022\017\n\007message\030\001 \001(\t2\331\001\n\024AccessControlSer" +
      "vice\022Z\n\013GrantAccess\022#.accesscontrolservi" +
      "ce.AccessRequest\032$.accesscontrolservice." +
      "AccessResponse0\001\022e\n\014RevokeAccess\022).acces" +
      "scontrolservice.RevokeAccessRequest\032*.ac" +
      "cesscontrolservice.RevokeAccessResponseB" +
      "?\n com.example.accesscontrolserviceB\031Acc" +
      "essControlServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_accesscontrolservice_AccessRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_accesscontrolservice_AccessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accesscontrolservice_AccessRequest_descriptor,
        new java.lang.String[] { "UserId", "AreaId", "AccessDuration", });
    internal_static_accesscontrolservice_AccessResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_accesscontrolservice_AccessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accesscontrolservice_AccessResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_accesscontrolservice_RevokeAccessRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_accesscontrolservice_RevokeAccessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accesscontrolservice_RevokeAccessRequest_descriptor,
        new java.lang.String[] { "UserId", "AreaId", });
    internal_static_accesscontrolservice_RevokeAccessResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_accesscontrolservice_RevokeAccessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_accesscontrolservice_RevokeAccessResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
