// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: accesscontrolservice.proto

package com.example.accesscontrolservice;

public interface RevokeAccessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:accesscontrolservice.RevokeAccessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string area_id = 2;</code>
   */
  java.lang.String getAreaId();
  /**
   * <code>string area_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getAreaIdBytes();
}
